version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "**"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "bun"
    directory: "crypto-ffi/bindings/js"
    schedule:
      interval: "daily"
    groups:
      js-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
