name: Fetch or make android package

runs:
  using: composite
  steps:
    - uses: actions/checkout@v5
    - name: download armv7-linux-androideabi binaries
      uses: ./.github/actions/make/android/lib
      with:
        task: android-armv7

    - name: download aarch64-linux-android binaries
      uses: ./.github/actions/make/android/lib
      with:
        task: android-armv8

    - name: download x86_64-linux-android binaries
      uses: ./.github/actions/make/android/lib
      with:
        task: android-x86

    - name: fetch ffi library
      uses: ./.github/actions/make/ffi-library

    - name: fetch uniffi bindgen artifact
      uses: ./.github/actions/make/uniffi-bindgen

    - name: make android
      uses: ./.github/actions/make
      with:
        key: android-${{ github.sha }}
        make-rule: android
        target-path: |
          crypto-ffi/bindings/android/build/outputs/aar
          crypto-ffi/bindings/android/src
