name: Fetch or make android package
inputs:
  gh-token:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v5
    - name: download armv7-linux-androideabi binaries
      uses: ./.github/actions/make/android/lib
      with:
        task: android-armv7
        gh-token: ${{ inputs.gh-token }}

    - name: download aarch64-linux-android binaries
      uses: ./.github/actions/make/android/lib
      with:
        task: android-armv8
        gh-token: ${{ inputs.gh-token }}

    - name: download x86_64-linux-android binaries
      uses: ./.github/actions/make/android/lib
      with:
        task: android-x86
        gh-token: ${{ inputs.gh-token }}

    - name: fetch ffi library
      uses: ./.github/actions/make/ffi-library
      with:
        gh-token: ${{ inputs.gh-token }}

    - name: fetch uniffi bindgen artifact
      uses: ./.github/actions/make/uniffi-bindgen
      with:
        gh-token: ${{ inputs.gh-token }}

    - name: make android bindings
      uses: ./.github/actions/make
      with:
        key: bindings-kotlin-android
        make-rule: bindings-kotlin-android
        target-path: |
          crypto-ffi/bindings/android/src/main/uniffi/com/wire/crypto/core_crypto_ffi.kt
        gh-token: ${{ inputs.gh-token }}

    - name: make android package
      uses: ./.github/actions/make
      with:
        key: android
        make-rule: android
        target-path: |
          target/armv7-linux-androideabi/release/libcore_crypto_ffi.a
          target/armv7-linux-androideabi/release/libcore_crypto_ffi.so
          target/aarch64-linux-android/release/libcore_crypto_ffi.a
          target/aarch64-linux-android/release/libcore_crypto_ffi.so
          target/x86_64-linux-android/release/libcore_crypto_ffi.a
          target/x86_64-linux-android/release/libcore_crypto_ffi.so
          crypto-ffi/bindings/android/build/outputs/aar/android-release.aar
          crypto-ffi/bindings/android/src/main/uniffi/com/wire/crypto/core_crypto_ffi.kt
        gh-token: ${{ inputs.gh-token }}
