name: Fetch or make uniffi-bindgen binary
inputs:
  gh-token:
    required: true

runs:
  using: composite

  steps:
    - name: Set MAKE
      uses: ./.github/actions/make/set-make-executable

    - name: write uniffi version file
      run: $MAKE .stamps/uniffi-version
      shell: bash -euo pipefail {0}

    - name: uniffi bindgen artifact name
      id: get-artifact-name
      run: |
        os="$(uname -s)"
        echo "artifact-name=uniffi-${os}" >> $GITHUB_OUTPUT
      shell: bash -euo pipefail {0}

    - uses: ./.github/actions/make
      with:
        key: ${{ steps.get-artifact-name.outputs.artifact-name }}
        make-rule: uniffi-bindgen
        target-path: target/release/uniffi-bindgen
        gh-token: ${{ inputs.gh-token }}

    - run: chmod +x target/release/uniffi-bindgen
      shell: bash -euo pipefail {0}
