name: Fetch or make the ffi lib for jvm linux
inputs:
  gh-token:
    required: true

runs:
  using: composite

  steps:
      - uses: ./.github/actions/make
        with:
          key: jvm-linux
          make-rule: jvm-linux
          target-path: target/x86_64-unknown-linux-gnu/release/libcore_crypto_ffi.so
          gh-token: ${{ inputs.gh-token }}
