concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-build-android"
  cancel-in-progress: true

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  RELEASE: 1

jobs:
  build-android:
    if: github.repository == 'wireapp/core-crypto'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - task: android-armv7
          - task: android-armv8
          - task: android-x86
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-and-cache-rust

      - name: build android lib
        uses: ./.github/actions/make/android/lib
        with:
          task: ${{ matrix.task }}
