concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-build-android"
  cancel-in-progress: true

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  RELEASE: 1

jobs:
  build-android:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - task: android-armv7
            target: armv7-linux-androideabi
          - task: android-armv8
            target: aarch64-linux-android
          - task: android-x86
            target: x86_64-linux-android
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-and-cache-rust
        with:
          target: ${{ matrix.target }}

      - name: build android lib
        uses: ./.github/actions/make/android/lib
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          task: ${{ matrix.task }}
