concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-build-jvm-linux"
  cancel-in-progress: true

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  RELEASE: 1

jobs:
  build-jvm:
    if: github.repository == 'wireapp/core-crypto'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-and-cache-rust
        with:
          target: "x86_64-unknown-linux-gnu"
      - name: build jvm-linux
        run: |
          make jvm-linux
      - name: upload dynamic library
        uses: actions/upload-artifact@v4
        with:
            name: jvm-linux-so-file-${{ github.run_id }}
            path: target/x86_64-unknown-linux-gnu/release/*.so
            retention-days: 1
      - name: upload bindings
        uses: actions/upload-artifact@v4
        with:
          name: jvm-linux-bindings-${{ github.run_id }}
          path: crypto-ffi/bindings
          retention-days: 1
