concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-docs-jvm"
  cancel-in-progress: true

on:
  workflow_call:

env:
  RELEASE: 1

jobs:
  docs-jvm:
    if: github.repository == 'wireapp/core-crypto'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: set up jdk 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "adopt"
      - name: gradle setup
        uses: gradle/actions/setup-gradle@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: download linux library
        uses: ./.github/actions/make/jvm-linux
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: download linux bindings
        uses: ./.github/actions/make/bindings-kotlin-jvm
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: run dokka
        run: |
            cd crypto-ffi/bindings
            ./gradlew android:dokkaGeneratePublicationHtml
            cd ..
            mkdir -p ../target/kotlin/doc
            cp -R bindings/android/build/dokka/html/ ../target/kotlin/doc
      - name: upload kotlin docs
        uses: actions/upload-artifact@v4.5.0
        with:
          name: kotlin
          path: target/kotlin/doc/html
          retention-days: 1
          overwrite: true
          include-hidden-files: true
          if-no-files-found: error
