concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-package-android"
  cancel-in-progress: true

on:
  workflow_call:

env:
  RELEASE: 1

jobs:
  package-android:
    if: github.repository == 'wireapp/core-crypto'
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: 28.1.13356709

    steps:
      - uses: actions/checkout@v5
      - name: set up jdk 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "adopt"
      - name: gradle setup
        uses: gradle/actions/setup-gradle@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup android sdk
        uses: android-actions/setup-android@v3
      - name: install ndk
        run: echo "y" | sdkmanager --install "ndk;$ANDROID_NDK_VERSION"
      - uses: ./.github/actions/make/android/package
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
