concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-package-ios"
  cancel-in-progress: true

on:
  workflow_call:

defaults:
  run:
    shell: bash -leo pipefail {0}

env:
  RELEASE: 1

jobs:
  package-ios:
    if: github.repository == 'wireapp/core-crypto' && github.event_name == 'pull_request'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5

      - name: download artifacts for ios device
        uses: ./.github/actions/make/ios
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          task: ios-device

      - name: download artifacts for ios simulator
        uses: ./.github/actions/make/ios
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          task: ios-simulator-arm

      - name: download swift bindings
        uses: ./.github/actions/make/bindings-swift
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4.0'
      - name: create xcframework
        run: |
          cd crypto-ffi/bindings/swift
          ./build-xcframework.sh
