name: publish android packages

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-publish-android"

on:
  workflow_call:
    secrets:
      SONATYPE_USERNAME:
        required: true
      SONATYPE_PASSWORD:
        required: true
      PGP_KEY_ID:
        required: true
      PGP_SIGNING_KEY:
        required: true
      PGP_PASSPHRASE:
        required: true

env:
  RELEASE: 1

jobs:
  publish-android:
    if: github.repository == 'wireapp/core-crypto'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: set up jdk 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "adopt"
      - name: gradle setup
        uses: gradle/actions/setup-gradle@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup android sdk
        uses: android-actions/setup-android@v3
      - uses: ./.github/actions/make/android/package
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: zip package and bindings
        run: |
          zip -r android.zip \
          crypto-ffi/bindings/android/build/outputs/aar/android-release.aar \
          crypto-ffi/bindings/android/src/main/uniffi/com/wire/crypto/core_crypto_ffi.kt

      - name: upload package
        uses: softprops/action-gh-release@v2
        with:
            files: android.zip
            fail_on_unmatched_files: true

      - name: publish package
        run: |
          cd crypto-ffi/bindings
          ./gradlew android:publishAllPublicationsToMavenCentralRepository --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.PGP_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.PGP_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.PGP_PASSPHRASE }}

      - name: delete package from gh release
        run: gh release delete-asset $GITHUB_REF_NAME android.zip --yes
        env:
          GH_TOKEN: ${{ github.token }}
