name: publish swift package

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-publish-swift"

on:
  workflow_call:

env:
  RELEASE: 1

jobs:
  publish-swift:
    if: github.repository == 'wireapp/core-crypto'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5

      - name: download artifacts for ios device
        uses: ./.github/actions/make/ios
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          task: ios-device

      - name: download artifacts for ios simulator
        uses: ./.github/actions/make/ios
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          task: ios-simulator-arm

      - name: download swift bindings
        uses: ./.github/actions/make/bindings-swift
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: download xcframework
        uses: ./.github/actions/make
        with:
          key: ios-create-xcframework
          make-rule: ios-create-xcframework
          target-path: |
              crypto-ffi/bindings/swift/WireCoreCrypto.xcframework.zip
              crypto-ffi/bindings/swift/WireCoreCryptoUniffi.xcframework.zip
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: upload xcframework
        uses: softprops/action-gh-release@v2
        with:
            files: |
              crypto-ffi/bindings/swift/WireCoreCrypto.xcframework.zip
              crypto-ffi/bindings/swift/WireCoreCryptoUniffi.xcframework.zip
            fail_on_unmatched_files: true
