name: publish node packages

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-publish-wasm"

on:
  workflow_call:

env:
  RELEASE: 1

jobs:
  publish-wasm:
    if: github.repository == 'wireapp/core-crypto'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: download ts artifacts
        uses: ./.github/actions/make/web/ts
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: zip package
        run: |
          zip -r web.zip \
          crypto-ffi/bindings/js/src/*

      - name: upload artifacts
        uses: softprops/action-gh-release@v2
        with:
            files: web.zip

      - name: publishes package to npm
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          package: "crypto-ffi/bindings/js/package.json"

      - name: delete package from gh release
        run: gh release delete-asset $GITHUB_REF_NAME web.zip --yes
        env:
          GH_TOKEN: ${{ github.token }}
