concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-test-ts"
  cancel-in-progress: true

on:
  workflow_call:

env:
  RELEASE: 1

jobs:
  test-ts:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: wireapp/setup-chrome@master
        id: setup-chrome
        with:
          chrome-version: stable
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: download web files
        uses: ./.github/actions/make/web/ts
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
      - name: lint
        run: |
          cd crypto-ffi/bindings/js
          bun eslint . --max-warnings=0
      - name: check all ts files
        run: |
          cd crypto-ffi/bindings/js
          bun tsc --noEmit
      - name: test
        run: make ts-test
