concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-test-jvm"
  cancel-in-progress: true

on:
  workflow_call:

env:
  RELEASE: 1

jobs:
  test-jvm:
    if: github.repository == 'wireapp/core-crypto' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: set up jdk 17
        uses: actions/setup-java@v5
        with:
          java-version: "17"
          distribution: "adopt"
      - name: gradle setup
        uses: gradle/actions/setup-gradle@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: download linux library
        uses: ./.github/actions/make/jvm-linux
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: download linux bindings
        uses: ./.github/actions/make/bindings-kotlin-jvm
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - name: run detekt
        run: |
          cd crypto-ffi/bindings
          ./gradlew jvm:detekt
      - name: build and test jvm package
        run: |
          cd crypto-ffi/bindings
          ./gradlew jvm:build -x lint -x lintRelease
